name: Scan Scheduler

on:
  schedule:
    - cron: "1 3,7,11,15,19,23 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python3.9 -m pip install --upgrade pip
        python3.9 -m pip install -r requirements.txt
    - name: Scan symbols
      env:
          BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
          BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}
          SLACK_URL: ${{ secrets.SLACK_URL }}
      run: |
        python signal_binance.py
